### ISSUE TITLE
blocks service - Service error Error [ERR_IPC_CHANNEL_CLOSED]

### ISSUE THREAD

**Issue by martinvillar** [rsksmart/rsk-explorer-api#33]
rsk-explorer-api v 1.0.2 

While syncing data from private MainNet node.

`Service error Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed at ChildProcess.target.send (internal/child_process.js:636:16) at send (/home/martin/Desktop/projects/rsk-explorer-api/src/services/blocks/index.js:41:19) at ChildProcess.parseMessage (/home/martin/Desktop/projects/rsk-explorer-api/src/services/blocks/index.js:57:32) at ChildProcess.emit (events.js:198:13) at ChildProcess.EventEmitter.emit (domain.js:448:20) at emit (internal/child_process.js:832:12) at process._tickCallback (internal/process/next_tick.js:63:19`

**Comment by emiliorizzo** [comment]
Hi @martinvillar, please include rsk-explorer-api version, thanks.

**Comment by martinvillar** [comment]
> Hi @martinvillar, please include rsk-explorer-api version, thanks.

edited comment, thanks.

**Comment by beexo-si** [comment]
Hi @martinvillar, the issue was closed without a solution, could you solve it on your own?
