### ISSUE TITLE
blocks service - VM execution errors

### ISSUE THREAD

**Issue by martinvillar** [rsksmart/rsk-explorer-api#34]
While syncing data from private MainNet node.

`Method name call Error: VM execution error: transaction reverted 
Method totalSupply call Error: VM execution error: transaction reverted 
Method symbol call Error: VM execution error: transaction reverted 
Method decimals call Error: VM execution error: transaction reverted 
Method balanceOf call Error: VM execution error: transaction reverted`

**Comment by emiliorizzo** [comment]
Hi @martinvillar. this is the expected behavior of explorer-api when the called contract does not support the method.
