### ISSUE TITLE
Can't verify SideToken on RSK Explorer

### ISSUE THREAD

**Issue by pmprete** [rsksmart/rsk-explorer-api#40]
I was able to verify it without troubles in Etherscan https://kovan.etherscan.io/address/0x69f6d4d4813f8e2e618dae7572e04b6d5329e207#code
But on RSK i keep getting an error 

<img width="1312" alt="Screen Shot 2020-04-23 at 15 45 52" src="https://user-images.githubusercontent.com/3655076/80137920-6417b100-857a-11ea-9d37-2a35e0c409a3.png">

This is the contract https://github.com/rsksmart/tokenbridge/blob/federated-testnet-deploy/bridge/contracts/SideToken.sol 

The address
https://explorer.testnet.rsk.co/address/0x0d86fca9be034a363cf12c9834af08d54a10451c

It was deployed using solc 0.5.12 and disabled optimization

**Comment by emiliorizzo** [comment]
https://explorer.testnet.rsk.co/address/0x0d86fca9be034a363cf12c9834af08d54a10451c

This contract was deployed by an internal transaction.
The current version of rsk-explorer-api doesn't support internal transactions.
This issue will be solved in the next release.

**Comment by pmprete** [comment]
Thank you! i'll mark it as resolved then.
