### ISSUE TITLE
docker-compose deploy error

### ISSUE THREAD

**Issue by liyaojian** [rsksmart/rsk-explorer-api#43]
E: The repository 'http://ppa.launchpad.net/rsksmart/rskj/ubuntu focal Release' does not have a Release file.
ERROR: Service 'rsk-node' failed to build: The command '/bin/sh -c add-apt-repository -y ppa:rsksmart/rskj &&   apt-get update &&   (echo rskj shared/accepted-rsk-license-v1-1 select true | /usr/bin/debconf-set-selections )&&   apt-get install -y --no-install-recommends rskj &&   apt-get clean &&   rm -rf /var/lib/apt/lists/* &&   rm -f /etc/rsk/node.conf &&   ln -s /etc/rsk/regtest.conf /etc/rsk/node.conf &&   rm -f /etc/rsk/regtest.conf' returned a non-zero code: 100

**Comment by francoode** [comment]
Try change /dockerized/rsk-node/Dockerfile 
FROM ubuntu:latest to FROM ubuntu:bionic

**Comment by liyaojian** [comment]
it works, thank you very much!
